import { PrismaClient } from '@prisma/client';
import { Users } from './users';

// ============================================================
//  LEADS — 17 leads across all pipeline stages
//
//  won      : LD-001, LD-002             → customer + opp + spec + quote + order
//  quoted   : LD-003                     → customer (prospect) + opp + spec + quote
//  qualified: LD-004, LD-005,            → opp + spec (in-progress / requested)
//             LD-013, LD-014, LD-015,
//             LD-016, LD-017
//  contacted: LD-006, LD-007, LD-008     → notes + follow-ups only (NO opportunity)
//  lost     : LD-009                     → closed_lost opportunity
//  new      : LD-010, LD-011, LD-012     → no downstream records
// ============================================================

export type LeadIds = Record<string, string>; // leadNumber → id

export async function seedLeads(prisma: PrismaClient, users: Users): Promise<LeadIds> {
  const { manager, salesperson, salesperson2 } = users;

  const leads = [
    // ── WON ──────────────────────────────────────────────────────────────────
    {
      leadNumber: 'LD-2026-0001',
      firstName: 'Dr. Suresh',
      lastName: 'Kumar',
      phone: '9876543210',
      email: 'suresh.kumar@medhospital.com',
      companyName: 'Medicare Multi-Specialty Hospital',
      designation: 'Medical Director',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560001',
      source: 'referral' as const,
      status: 'won' as const,
      priority: 'high' as const,
      productType: 'air_purifier' as const,
      estimatedValue: 452000,
      requirementNotes: 'Air purifiers for 3 ICU wards and 10 general wards. Total area ~8000 sqft.',
      assignedToId: salesperson.id,
      createdById: manager.id,
      convertedAt: new Date('2026-02-10'),
      convertedById: salesperson.id,
    },
    {
      leadNumber: 'LD-2026-0002',
      firstName: 'Kavitha',
      lastName: 'Reddy',
      phone: '9432109876',
      email: 'kavitha@apolloclinic.com',
      companyName: 'Apollo Clinic',
      designation: 'Administrator',
      city: 'Hyderabad',
      state: 'Telangana',
      pincode: '500001',
      source: 'referral' as const,
      status: 'won' as const,
      priority: 'high' as const,
      productType: 'air_purifier' as const,
      estimatedValue: 318000,
      requirementNotes: 'Air purifiers for clinic reception, 3 consultation rooms and lab.',
      assignedToId: salesperson2.id,
      createdById: salesperson2.id,
      convertedAt: new Date('2026-03-01'),
      convertedById: salesperson2.id,
    },
    // ── QUOTED ───────────────────────────────────────────────────────────────
    {
      leadNumber: 'LD-2026-0003',
      firstName: 'Vikram',
      lastName: 'Bose',
      phone: '9543210987',
      email: 'vikram@greenbuilders.com',
      companyName: 'Green Builders Pvt Ltd',
      designation: 'Project Director',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600001',
      source: 'exhibition' as const,
      status: 'quoted' as const,
      priority: 'urgent' as const,
      productType: 'hvac' as const,
      estimatedValue: 2450000,
      requirementNotes: 'Complete HVAC solution for new 50,000 sqft commercial complex.',
      assignedToId: salesperson.id,
      createdById: manager.id,
    },
    // ── QUALIFIED ────────────────────────────────────────────────────────────
    {
      leadNumber: 'LD-2026-0004',
      firstName: 'Anand',
      lastName: 'Mehta',
      phone: '9765432109',
      email: 'anand@techcorp.in',
      companyName: 'TechCorp Industries',
      designation: 'Facility Manager',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411001',
      source: 'website' as const,
      status: 'qualified' as const,
      priority: 'high' as const,
      productType: 'industrial_solution' as const,
      estimatedValue: 1250000,
      requirementNotes: 'Industrial air purification for manufacturing plant. Heavy dust and metal particle environment.',
      assignedToId: salesperson.id,
      createdById: salesperson.id,
    },
    {
      leadNumber: 'LD-2026-0005',
      firstName: 'Ravi',
      lastName: 'Shankar',
      phone: '9098765432',
      email: 'ravi.shankar@iisc.ac.in',
      companyName: 'IISc Research Labs',
      designation: 'Lab Director',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560012',
      source: 'referral' as const,
      status: 'qualified' as const,
      priority: 'medium' as const,
      productType: 'industrial_solution' as const,
      estimatedValue: 1800000,
      requirementNotes: 'Research-grade HEPA filtration and laminar flow for 5 labs. ISO Class 5 cleanroom standards.',
      assignedToId: salesperson.id,
      createdById: manager.id,
    },
    // ── CONTACTED ────────────────────────────────────────────────────────────
    {
      leadNumber: 'LD-2026-0006',
      firstName: 'Mohammed',
      lastName: 'Ilyas',
      phone: '9321098765',
      email: 'ilyas@palacehotel.in',
      companyName: 'Palace Grand Hotel',
      designation: 'General Manager',
      city: 'Kochi',
      state: 'Kerala',
      pincode: '682001',
      source: 'referral' as const,
      status: 'contacted' as const,
      priority: 'medium' as const,
      productType: 'air_purifier' as const,
      estimatedValue: 680000,
      requirementNotes: 'Hotel lobby, 45 rooms, restaurant and banquet hall.',
      nextFollowUpDate: new Date('2026-04-25'),
      assignedToId: salesperson.id,
      createdById: manager.id,
    },
    {
      leadNumber: 'LD-2026-0007',
      firstName: 'Priyanka',
      lastName: 'Singh',
      phone: '9654321098',
      email: 'priyanka.singh@gmail.com',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400001',
      source: 'cold_call' as const,
      status: 'contacted' as const,
      priority: 'low' as const,
      productType: 'moscure' as const,
      estimatedValue: 85000,
      requirementNotes: 'Residential 3BHK. Interested in Moscure home solution.',
      nextFollowUpDate: new Date('2026-04-22'),
      assignedToId: salesperson2.id,
      createdById: salesperson2.id,
    },
    {
      leadNumber: 'LD-2026-0008',
      firstName: 'Nisha',
      lastName: 'Thomas',
      phone: '9987654321',
      email: 'nisha@thomasbakery.com',
      companyName: 'Thomas Bakery & Cafe',
      designation: 'Owner',
      city: 'Thrissur',
      state: 'Kerala',
      pincode: '680001',
      source: 'walk_in' as const,
      status: 'contacted' as const,
      priority: 'low' as const,
      productType: 'moscure' as const,
      estimatedValue: 95000,
      requirementNotes: 'Bakery outlet. Strong odor control needed for adjacent cafe.',
      nextFollowUpDate: new Date('2026-04-24'),
      assignedToId: salesperson2.id,
      createdById: salesperson2.id,
    },
    // ── LOST ─────────────────────────────────────────────────────────────────
    {
      leadNumber: 'LD-2026-0009',
      firstName: 'Deepak',
      lastName: 'Kulkarni',
      phone: '9109876543',
      email: 'deepak@kulkarnipharma.com',
      companyName: 'Kulkarni Pharmaceuticals',
      designation: 'Operations Head',
      city: 'Nashik',
      state: 'Maharashtra',
      pincode: '422001',
      source: 'exhibition' as const,
      status: 'lost' as const,
      priority: 'medium' as const,
      productType: 'industrial_solution' as const,
      estimatedValue: 900000,
      lostReason: 'Budget constraints — deferred to next financial year.',
      requirementNotes: 'Clean room air handling for pharmaceutical manufacturing.',
      assignedToId: salesperson.id,
      createdById: salesperson.id,
    },
    // ── QUALIFIED (additional) ──────────────────────────────────────────────
    {
      leadNumber: 'LD-2026-0013',
      firstName: 'Dr. Pradeep',
      lastName: 'Menon',
      phone: '9312345678',
      email: 'pradeep.menon@fortishospital.com',
      companyName: 'Fortis Hospital',
      designation: 'Chief Medical Officer',
      city: 'Delhi',
      state: 'Delhi',
      pincode: '110017',
      source: 'referral' as const,
      status: 'qualified' as const,
      priority: 'high' as const,
      productType: 'air_purifier' as const,
      estimatedValue: 780000,
      requirementNotes: 'Air purifiers for 5 ICU wards and 20 general wards. New wing inauguration in July.',
      assignedToId: salesperson.id,
      createdById: manager.id,
    },
    {
      leadNumber: 'LD-2026-0014',
      firstName: 'Rohit',
      lastName: 'Kapoor',
      phone: '9823456789',
      email: 'rohit.kapoor@hyattmumbai.com',
      companyName: 'Hyatt Regency Mumbai',
      designation: 'Director of Engineering',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400051',
      source: 'exhibition' as const,
      status: 'qualified' as const,
      priority: 'medium' as const,
      productType: 'air_purifier' as const,
      estimatedValue: 1100000,
      requirementNotes: 'Hotel-wide air quality upgrade. 250 rooms, lobby, 3 restaurants, conference halls.',
      assignedToId: salesperson.id,
      createdById: manager.id,
    },
    {
      leadNumber: 'LD-2026-0015',
      firstName: 'Sunil',
      lastName: 'Verma',
      phone: '9734567890',
      email: 'sunil.verma@reliance.com',
      companyName: 'Reliance Industries — Warehouse Division',
      designation: 'Head of Facilities',
      city: 'Navi Mumbai',
      state: 'Maharashtra',
      pincode: '400708',
      source: 'partner' as const,
      status: 'qualified' as const,
      priority: 'urgent' as const,
      productType: 'industrial_solution' as const,
      estimatedValue: 3200000,
      requirementNotes: 'Industrial air handling for 3 distribution warehouses. Total area 1.2 lakh sqft.',
      assignedToId: salesperson.id,
      createdById: manager.id,
    },
    {
      leadNumber: 'LD-2026-0016',
      firstName: 'Fr. Joseph',
      lastName: 'D\'Souza',
      phone: '9645678901',
      email: 'principal@stxaviers.edu.in',
      companyName: "St. Xavier's College",
      designation: 'Principal',
      city: 'Ahmedabad',
      state: 'Gujarat',
      pincode: '380009',
      source: 'social_media' as const,
      status: 'qualified' as const,
      priority: 'medium' as const,
      productType: 'air_purifier' as const,
      estimatedValue: 520000,
      requirementNotes: 'Air purifiers for 35 classrooms, library, and staff rooms. PM2.5 levels high in area.',
      assignedToId: salesperson2.id,
      createdById: salesperson2.id,
    },
    {
      leadNumber: 'LD-2026-0017',
      firstName: 'Dr. Shweta',
      lastName: 'Nambiar',
      phone: '9556789012',
      email: 'shweta.nambiar@manipal.edu',
      companyName: 'Manipal Hospital Bangalore',
      designation: 'Hospital Administrator',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560017',
      source: 'referral' as const,
      status: 'qualified' as const,
      priority: 'high' as const,
      productType: 'air_purifier' as const,
      estimatedValue: 650000,
      requirementNotes: 'Replacement of old air handling units. 4 OT suites and 8 ICU beds.',
      assignedToId: salesperson2.id,
      createdById: manager.id,
    },
    // ── NEW ──────────────────────────────────────────────────────────────────
    {
      leadNumber: 'LD-2026-0010',
      firstName: 'Sunita',
      lastName: 'Agarwal',
      phone: '9210987654',
      email: 'sunita@agarwalschool.com',
      companyName: 'Agarwal Public School',
      designation: 'Principal',
      city: 'Jaipur',
      state: 'Rajasthan',
      pincode: '302001',
      source: 'social_media' as const,
      status: 'new' as const,
      priority: 'low' as const,
      productType: 'air_purifier' as const,
      estimatedValue: 250000,
      requirementNotes: 'Air purifiers for 20 classrooms and staffroom.',
      assignedToId: salesperson2.id,
      createdById: salesperson2.id,
    },
    {
      leadNumber: 'LD-2026-0011',
      firstName: 'Sanjay',
      lastName: 'Malhotra',
      phone: '9111222333',
      email: 'sanjay@malhotramall.com',
      companyName: 'Malhotra Shopping Mall',
      designation: 'Operations Head',
      city: 'Delhi',
      state: 'Delhi',
      pincode: '110001',
      source: 'walk_in' as const,
      status: 'new' as const,
      priority: 'medium' as const,
      productType: 'air_purifier' as const,
      estimatedValue: 900000,
      requirementNotes: 'Mall-wide air quality improvement. 3 floors, food court, anchor stores.',
      assignedToId: salesperson.id,
      createdById: manager.id,
    },
    {
      leadNumber: 'LD-2026-0012',
      firstName: 'Latha',
      lastName: 'Iyer',
      phone: '9444555666',
      email: 'latha.iyer@gmail.com',
      city: 'Coimbatore',
      state: 'Tamil Nadu',
      pincode: '641001',
      source: 'social_media' as const,
      status: 'new' as const,
      priority: 'low' as const,
      productType: 'moscure' as const,
      estimatedValue: 45000,
      requirementNotes: 'Individual home. Looking for Moscure M1 unit for bedroom.',
      assignedToId: salesperson2.id,
      createdById: salesperson2.id,
    },
  ];

  const ids: LeadIds = {};
  for (const lead of leads) {
    const created = await prisma.lead.upsert({
      where: { leadNumber: lead.leadNumber },
      update: {},
      create: lead,
    });
    ids[lead.leadNumber] = created.id;
  }

  // ── Lead Notes ──────────────────────────────────────────────────────────────
  await prisma.leadNote.createMany({
    data: [
      { leadId: ids['LD-2026-0001'], note: 'Referral from Dr. Arora. Called and fixed a site visit.', noteType: 'call', createdById: salesperson.id },
      { leadId: ids['LD-2026-0001'], note: 'Site visit done. Measured all wards. Director very cooperative.', noteType: 'site_inspection', createdById: salesperson.id },
      { leadId: ids['LD-2026-0001'], note: 'Submitted quotation. Hospital admin reviewing with purchase committee.', noteType: 'general', createdById: salesperson.id },
      { leadId: ids['LD-2026-0002'], note: 'Referral from Medicare Hospital (LD-001). Apollo is expanding rapidly.', noteType: 'general', createdById: salesperson2.id },
      { leadId: ids['LD-2026-0002'], note: 'Site inspection at clinic done. 6 units recommended by design team.', noteType: 'site_inspection', createdById: salesperson2.id },
      { leadId: ids['LD-2026-0003'], note: 'Met at Acetech Exhibition Bangalore. Very serious HVAC requirement.', noteType: 'meeting', createdById: salesperson.id },
      { leadId: ids['LD-2026-0003'], note: 'Design spec completed. Quotation sent. Waiting for consultant approval.', noteType: 'general', createdById: salesperson.id },
      { leadId: ids['LD-2026-0004'], note: 'Enquiry via website. Called back, fixed factory demo visit.', noteType: 'call', createdById: salesperson.id },
      { leadId: ids['LD-2026-0004'], note: 'Factory site visit done. PM levels very high. Design team looped in.', noteType: 'site_inspection', createdById: salesperson.id },
      { leadId: ids['LD-2026-0005'], note: 'IISc is a long-cycle government procurement. Design review in early stage.', noteType: 'general', createdById: manager.id },
      { leadId: ids['LD-2026-0013'], note: 'Referral from Medicare Hospital. Fortis CMO met at a medical conference. New wing needs full air purification setup.', noteType: 'meeting', createdById: salesperson.id },
      { leadId: ids['LD-2026-0014'], note: 'Met at HospEx exhibition. Hotel undergoing renovation — ideal timing for air quality upgrade.', noteType: 'meeting', createdById: salesperson.id },
      { leadId: ids['LD-2026-0015'], note: 'Partner referral. Reliance facility head very serious. Wants demo at one warehouse first.', noteType: 'call', createdById: salesperson.id },
      { leadId: ids['LD-2026-0016'], note: 'Enquiry via Instagram ad. Principal called directly. Budget pre-approved by trust.', noteType: 'call', createdById: salesperson2.id },
      { leadId: ids['LD-2026-0017'], note: 'Referral from Dr. Suresh Kumar (Medicare). OT and ICU renewal project. Urgent requirement.', noteType: 'general', createdById: salesperson2.id },
      { leadId: ids['LD-2026-0006'], note: 'First call done. Hotel GM interested. Site visit scheduled for next week.', noteType: 'call', createdById: salesperson.id },
      { leadId: ids['LD-2026-0007'], note: 'Cold call response. Customer interested in Moscure M2 for living room.', noteType: 'call', createdById: salesperson2.id },
      { leadId: ids['LD-2026-0009'], note: 'Lost — budget deferred. Keep warm for Q3 follow-up.', noteType: 'status_change', createdById: manager.id },
    ],
    skipDuplicates: true,
  });

  // ── Follow-ups ──────────────────────────────────────────────────────────────
  await prisma.leadFollowUp.createMany({
    data: [
      { leadId: ids['LD-2026-0003'], scheduledDate: new Date('2026-04-05'), scheduledTime: '11:00', description: 'Follow up on quotation status with consultant', status: 'completed', outcome: 'Consultant reviewed. Minor revision needed on duct sizing.', completedAt: new Date('2026-04-05T11:30:00'), assignedToId: salesperson.id, createdById: salesperson.id },
      { leadId: ids['LD-2026-0004'], scheduledDate: new Date('2026-04-20'), scheduledTime: '10:00', description: 'Demo of industrial scrubber at factory site', status: 'pending', assignedToId: salesperson.id, createdById: salesperson.id },
      { leadId: ids['LD-2026-0005'], scheduledDate: new Date('2026-04-28'), scheduledTime: '14:00', description: 'Meeting with IISc procurement officer', status: 'pending', assignedToId: salesperson.id, createdById: manager.id },
      { leadId: ids['LD-2026-0006'], scheduledDate: new Date('2026-04-25'), scheduledTime: '10:00', description: 'Site inspection at Palace Grand Hotel', status: 'pending', assignedToId: salesperson.id, createdById: manager.id },
      { leadId: ids['LD-2026-0007'], scheduledDate: new Date('2026-04-22'), scheduledTime: '15:00', description: 'Product demo at customer home', status: 'pending', assignedToId: salesperson2.id, createdById: salesperson2.id },
      { leadId: ids['LD-2026-0008'], scheduledDate: new Date('2026-04-10'), scheduledTime: '11:00', description: 'Visited bakery. Customer liked Moscure M2. Sending quote.', status: 'completed', outcome: 'Customer liked Moscure M2. Will discuss with partner before deciding.', completedAt: new Date('2026-04-10T12:00:00'), assignedToId: salesperson2.id, createdById: salesperson2.id },
    ],
    skipDuplicates: true,
  });

  console.log(`✅ 17 leads, notes & follow-ups created`);
  return ids;
}
